# Linear Algebra with Python

In [42]:
import numpy as np

## 2. Using NumPy Arrays

- The core of using NumPy effectively for linear algebra is using NumPy arrays. 
- NumPy arrays are n-dimensional array data structures that can be used to represent both vectors (1-dimensional array) and matrices (2-dimensional arrays).
- A NumPy array is initialized using the `np.array()` function, and including a Python list argument or Python nested list argument for arrays with more than one dimension.
- For example, the following creates a NumPy array representation of a vector:

In [3]:
v = np.array([1, 2, 3, 4, 5, 6])

- We can also create a matrix, which is the equivalent of a two-dimensional NumPy array, using a nested Python list:

In [5]:
A = np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

- Matrices can also be created by combining existing vectors using the `np.column_stack()` function:

In [6]:
v = np.array([-2,-2,-2,-2])
u = np.array([0,0,0,0])
w = np.array([3,3,3,3])

A = np.column_stack((v, u, w))
A

array([[-2,  0,  3],
       [-2,  0,  3],
       [-2,  0,  3],
       [-2,  0,  3]])

- To access the shape of a matrix or vector once it’s been created as a NumPy array, we call the `.shape` attribute of the array variable:

In [7]:
A = np.array([[1,2],[3,4]])
A.shape

(2, 2)

- To access individual elements in a NumPy array, we can index the array using square brackets. 
- Unlike regular Python lists, we can index into all dimensions in a single square bracket, separating the dimension indices with commas.
- Thus in order to index the element equal to 2 in matrix A, we can do the following:

In [8]:
A = np.array([[1,2],[3,4]])
A[0,1]

np.int64(2)

- We can also select a subset or entire dimension of a NumPy array using a colon. 
- For example, if we want the entire second column of a matrix, we can index the second column and use an empty colon to select every row as such:

In [9]:
A = np.array([[1,2],[3,4]])
A[:,1]

array([2, 4])

Note: `[2 4]` is a column vector, but it outputs in the terminal horizontally.

### Tasks

**Task 1**  
- Three NumPy arrays are preloaded in for you: `vector_1`, `vector_2`, and `vector_3`. Use `.column_stack()` to combine these three arrays into a 4x3 matrix. 
- Save this value to a variable called `matrix`.
- In your matrix:
    - `vector_1` should be the first column.
    - `vector_2` should be the second column.
    - `vector_3` should be the third column.
- Print out `matrix` as well so you see its output in the terminal.

<br>

**Task 2**  
- Print out the shape of `matrix` into the output terminal.

<br>

**Task 3**  
- Use array indexing to print out the third column of `matrix` in the output terminal.

In [10]:
# Given vectors
vector_1 = np.array([-2,-6,2,3])
vector_2 = np.array([4,1,-3,8])
vector_3 = np.array([5,-7,9,0])

In [13]:
# Task 1
matrix = np.column_stack((vector_1, vector_2, vector_3))
print(matrix)

# Task 2
print(matrix.shape)

# Task 3
print(matrix[:,2])

[[-2  4  5]
 [-6  1 -7]
 [ 2 -3  9]
 [ 3  8  0]]
(4, 3)
[ 5 -7  9  0]


## 3. Using NumPy for Linear Algebra Operations

- Now that we know how to use NumPy arrays to create vectors and matrices, we can learn how to perform various linear algebra operations using Python.
- To multiply a vector or matrix by a scalar, we use inbuilt Python multiplication between the NumPy array and the scalar:

<br>

- Written out mathematically, this is:
$$
4 \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix} = \begin{bmatrix} 4 & 8 \\ 12 & 16 \end{bmatrix}

In [16]:
A = np.array([[1,2],[3,4]])
4 * A

array([[ 4,  8],
       [12, 16]])

- To add equally sized vectors or matrices, we can again use inbuilt Python addition between the NumPy arrays.

<br>

- Written out mathematically, this is:
$$
\begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix} + \begin{bmatrix} -4 & -3 \\ -2 & -1 \end{bmatrix} = \begin{bmatrix} -3 & -1 \\ 1 & 3 \end{bmatrix}
$$

In [17]:
A = np.array([[1,2],[3,4]])
B = np.array([[-4,-3],[-2,-1]])
A + B

array([[-3, -1],
       [ 1,  3]])

- Vector dot products can be computed using the `np.dot()` function:

<br>

- Written out mathematically, this is:
$$
\begin{bmatrix} -1 \\ -2 \\ -3 \end{bmatrix} \cdot \begin{bmatrix} 2 \\ 2 \\ 2 \end{bmatrix} = -12

In [18]:
v = np.array([-1,-2,-3])
u = np.array([2,2,2])
np.dot(v,u)

np.int64(-12)

- Matrix multiplication is computed using either the `np.matmul()` function or using the `@` symbol as shorthand. 
- It is important to note that using the typical Python multiplication symbol `*` will result in an elementwise multiplication instead.

<br>

- Written out mathematically, this is:
$$
\begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix} \cdot \begin{bmatrix} -4 & -3 \\ -2 & -1 \end{bmatrix} = \begin{bmatrix} -8 & -5 \\ -20 & -13 \end{bmatrix}
$$

In [23]:
A = np.array([[1,2],[3,4]])
B = np.array([[-4,-3],[-2,-1]])

# one way to matrix multiply
print(np.matmul(A,B))
# another way to matrix multiply
print(A @ B)

[[ -8  -5]
 [-20 -13]]
[[ -8  -5]
 [-20 -13]]


### Tasks

**Task 1**  
- Calculate the following equation using NumPy:
$$ D = 4A - 2B $$
- Save your equation to a variable called `D` and print it in the output terminal. 
- Try calculating by hand before or after using Python to verify you understand how the operation works!

<br>

**Task 2**  
- Calculate the following matrix multiplication equation using NumPy:
$$ E = AC $$
- Save your equation to a variable called `E` and print it in the output terminal. 
- Try calculating by hand before or after using Python to verify you understand how the operation works!

<br>

**Task 3**  
- Calculate the following matrix multiplication equation using NumPy:
$$ F = CA $$
- Save your equation to a variable called `F` and print it in the output terminal. 
- Try calculating by hand before or after using Python to verify you understand how the operation works!

In [25]:
# Given
# 2 x 3 matrix
A = np.array([[2,3,-4], [-2, 1, -3]])
# 2 x 3 matrix
B = np.array([[1,-1,4], [3,-3,3]])
# 3 x 2 matrix
C = np.array([[1, 2], [3, 4], [5, 6]])

A.shape, B.shape, C.shape

((2, 3), (2, 3), (3, 2))

**Task 1**  
- Calculating by hand:
$$ D = 4A - 2B $$
$$ D = 4 \begin{bmatrix} 2 & 3 & -4 \\ -2 & 1 & -3 \end{bmatrix} - 2 \begin{bmatrix} 1 & -1 & 4 \\ 3 & -3 & 3 \end{bmatrix} = \begin{bmatrix} 8 & 12 & -16 \\ -8 & 4 & -12 \end{bmatrix} - \begin{bmatrix} 2 & -2 & 8 \\ 6 & -6 & 6 \end{bmatrix} = \begin{bmatrix} 6 & 14 & -24 \\ -14 & 10 & -18 \end{bmatrix} $$

In [26]:
# Task 1
D = 4*A - 2*B
D

array([[  6,  14, -24],
       [-14,  10, -18]])

**Task 2**
- Calculating by hand:
$$ E = AC $$
$$ E = \begin{bmatrix} 2 & 3 & -4 \\ -2 & 1 & -3 \end{bmatrix} \begin{bmatrix} 1 & 2 \\ 3 & 4 \\ 5 & 6 \end{bmatrix} = \begin{bmatrix} 2 \cdot 1 + 3 \cdot 3 + (-4) \cdot 5 & 2 \cdot 2 + 3 \cdot 4 + (-4) \cdot 6 \\ (-2) \cdot 1 + 1 \cdot 3 + (-3) \cdot 5 & (-2) \cdot 2 + 1 \cdot 4 + (-3) \cdot 6 \end{bmatrix} = \begin{bmatrix} 2 + 9 - 20 & 4 + 12 - 24 \\ -2 + 3 - 15 & -4 + 4 - 18 \end{bmatrix} = \begin{bmatrix} -9 & -8 \\ -14 & -18 \end{bmatrix} $$

In [28]:
E = A @ C
E

array([[ -9,  -8],
       [-14, -18]])

**Task 3**
- Calculating by hand:
$$ F = CA $$
$$ F = \begin{bmatrix} 1 & 2 \\ 3 & 4 \\ 5 & 6 \end{bmatrix} \begin{bmatrix} 2 & 3 & -4 \\ -2 & 1 & -3 \end{bmatrix} = \begin{bmatrix} 1 \cdot 2 + 2 \cdot (-2) & 1 \cdot 3 + 2 \cdot 1 & 1 \cdot (-4) + 2 \cdot (-3) \\ 3 \cdot 2 + 4 \cdot (-2) & 3 \cdot 3 + 4 \cdot 1 & 3 \cdot (-4) + 4 \cdot (-3) \\ 5 \cdot 2 + 6 \cdot (-2) & 5 \cdot 3 + 6 \cdot 1 & 5 \cdot (-4) + 6 \cdot (-3) \end{bmatrix} = \begin{bmatrix} 2 - 4 & 3 + 2 & -4 - 6 \\ 6 - 8 & 9 + 4 & -12 - 12 \\ 10 - 12 & 15 + 6 & -20 - 18 \end{bmatrix} = \begin{bmatrix} -2 & 5 & -10 \\ -2 & 13 & -24 \\ -2 & 21 & -38 \end{bmatrix} $$

In [29]:
F = C @ A
F

array([[ -2,   5, -10],
       [ -2,  13, -24],
       [ -2,  21, -38]])

## 4. Special Matrices

- In addition to having built-in support for many linear algebra-related operations, Let’s see how NumPy can create special matrices, such as the identity matrix.
- An identity matrix can be constructed using the `np.eye()` functions, which takes an integer argument that determines the *n x n* size of the square identity matrix.

In [30]:
identity = np.eye(4)
identity

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

- A matrix or vector of all zeros can be constructed using the `np.zeros()` function, which takes in a tuple argument for the shape of the NumPy array filled with zeros.

In [31]:
# 5-element vector of zeros
zero_vector = np.zeros((5))
zero_vector

array([0., 0., 0., 0., 0.])

In [32]:
# 3x2 matrix of zeros
zero_matrix = np.zeros((3,2))
zero_matrix

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

- The transpose of a matrix can be accessed using the `.T` attribute of a NumPy array as shown below:

In [34]:
A = np.array([[1,2],[3,4]])
A_transpose = A.T
A, A_transpose

(array([[1, 2],
        [3, 4]]),
 array([[1, 3],
        [2, 4]]))

- Since `A_transpose` is the transpose of `A`, the rows and columns are swapped.

### Tasks

**Task 1**  
- Two NumPy arrays are given, `A` and `B`, representing two 3x3 matrices. 
- Print out the matrix product of `AB` and the matrix product of `BA`.
- What does this say about the relationship between matrix `A` and matrix `B`?

<br>

**Task 2**  
- Print out the transpose of both matrix `A` and matrix `B`. 
- What is the first row of each transposed matrix?

In [37]:
# Given
A = np.array([[1,-1,1], [0,1,0], [-1,2,1]])
B = np.array([[0.5,1.5,-0.5], [0,1,0], [0.5,-0.5,0.5]])
A, B

(array([[ 1, -1,  1],
        [ 0,  1,  0],
        [-1,  2,  1]]),
 array([[ 0.5,  1.5, -0.5],
        [ 0. ,  1. ,  0. ],
        [ 0.5, -0.5,  0.5]]))

In [39]:
# Task 1
A@B, B@A    # They are the inverse of each other

(array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]),
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]))

In [41]:
# Task 2
A.T, B.T    # The first row is the first column of the original matrix

(array([[ 1,  0, -1],
        [-1,  1,  2],
        [ 1,  0,  1]]),
 array([[ 0.5,  0. ,  0.5],
        [ 1.5,  1. , -0.5],
        [-0.5,  0. ,  0.5]]))

## 5. Additional Linear Algebra Operations

- Moving past special matrices, there are some more advanced linear algebra operations we can perform using NumPy. 
- To start, we will be using the `numpy.linalg` sublibrary to perform the following operations:
- The “norm” (or length/magnitude) of a vector can be found using the `np.linalg.norm()` function.

In [44]:
v = np.array([2,-4,1])
v_norm = np.linalg.norm(v)
v_norm

np.float64(4.58257569495584)

- The inverse of a square matrix, if one exists, can be found using `np.linalg.inv()`:

In [45]:
A = np.array([[1,2],[3,4]])
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

- Finally, we can actually solve for unknown variables in a system on linear equations in *Ax=b* form using `np.linalg.solve()`, which takes in the *A* and *b* parameters. 
- Given:
$$
x + 4y - z = -1 \\
-x - 3y + 2z = 2 \\
2x - y - 2z = -2
$$

- We convert to *Ax=b* form and solve.

In [47]:
# each array in A is an equation from the above system of equations
A = np.array([[1,4,-1],[-1,-3,2],[2,-1,-2]])
# the solution to each equation
b = np.array([-1,2,-2])
# solve for x, y, and z
x,y,z = np.linalg.solve(A,b)
x, y, z

(np.float64(0.0), np.float64(0.0), np.float64(1.0))

### Tasks

**Task 1**  
- We have a system of equations written out. 
- Let’s put this in the form *Ax=b* and solve the system using NumPy.
- First, let’s define *A* using a NumPy array. 
- Save this NumPy array in a variable called `A`.
-  When you define `A`, pay attention to the coefficients in each equation.

<br>

**Task 2**  
- We now need the *b* part of our *Ax=b* form.
- Create a NumPy array in a variable named `b` that represents the system of equations given.

<br>

**Task 3**  
- Use `np.linalg.solve()` to solve *Ax=b*. Use the variables `x`, `y`, and `z` to represent the solutions.
- After using `np.linalg.solve()`, use the following line of code to view the solution to the system of equations:

In [48]:
# Given
'''
4x + z = 2
-y + 2z - 3x = 0
.5y - x - 1.5z = -4
'''

'\n4x + z = 2\n-y + 2z - 3x = 0\n.5y - x - 1.5z = -4\n'

In [51]:
# Task 1
A = np.array([[4, 0, 1],[-3, -1, 2],[-1, .5, -1.5]])

# Task 2
b = np.array([2, 0, -4])

# Task 3
x, y, z = np.linalg.solve(A,b)
x, y, z

(np.float64(6.0), np.float64(-62.0), np.float64(-22.0))

## 6. Review

- Using what you have learned in this lesson, find the unknowns `a`, `b`, `c`, and `d`. 

In [54]:
# Given
'''
2a + 3d - 2c = 4
-c + 4b - a = 1
2d - 2c + 3a - b = 2
-2a + 3c - b = -2
'''

'\n2a + 3d - 2c = 4\n-c + 4b - a = 1\n2d - 2c + 3a - b = 2\n-2a + 3c - b = -2\n'

In [55]:
A = np.array([[2, 0, -2, 3], [-1, 4, -1, 0], [3, -1, -2, 2], [-2, -1, 3, 0]])
print(A)

z = np.array([4, 1, 2, -2])
print(z)

a, b, c, d = np.linalg.solve(A, z)
print((a, b, c, d))

[[ 2  0 -2  3]
 [-1  4 -1  0]
 [ 3 -1 -2  2]
 [-2 -1  3  0]]
[ 4  1  2 -2]
(np.float64(-1.4999999999999998), np.float64(-0.5909090909090906), np.float64(-1.8636363636363633), np.float64(1.0909090909090908))
